package DND_QUIZ;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import ConnectionProvider.ConnectionProvider;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;

/**
 * Kelas DeleteQuestion adalah GUI untuk menghapus pertanyaan dari database.
 * User dapat mencari dan menghapus pertanyaan berdasarkan ID
 * 
 * @author DAFFA
 */
public class DeleteQuestion extends javax.swing.JFrame {

    /**
     * Konstruktor untuk inisialisasi frame DeleteQuestion.
     * Memanggil initComponents untuk menginisialisasi komponen GUI.
     */
    public DeleteQuestion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeBtn = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        txtQuestion = new javax.swing.JTextField();
        txtOpt1 = new javax.swing.JTextField();
        txtOpt2 = new javax.swing.JTextField();
        txtOpt3 = new javax.swing.JTextField();
        txtOpt4 = new javax.swing.JTextField();
        txtAnswer = new javax.swing.JTextField();
        deleteBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(140, 120));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_backgrounds_images/logo exit (1).png"))); // NOI18N
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 50, 50));

        txtID.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtID.setMinimumSize(new java.awt.Dimension(64, 32));
        txtID.setPreferredSize(new java.awt.Dimension(64, 32));
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 230, 40));

        searchBtn.setBackground(new java.awt.Color(34, 162, 216));
        searchBtn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, -1, -1));

        txtQuestion.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtQuestion.setFocusable(false);
        getContentPane().add(txtQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 700, -1));

        txtOpt1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtOpt1.setFocusable(false);
        getContentPane().add(txtOpt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 700, -1));

        txtOpt2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtOpt2.setFocusable(false);
        getContentPane().add(txtOpt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 700, -1));

        txtOpt3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtOpt3.setFocusable(false);
        getContentPane().add(txtOpt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 700, -1));

        txtOpt4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtOpt4.setFocusable(false);
        getContentPane().add(txtOpt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 700, -1));

        txtAnswer.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtAnswer.setFocusable(false);
        getContentPane().add(txtAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 700, -1));

        deleteBtn.setBackground(new java.awt.Color(34, 162, 216));
        deleteBtn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 457, -1, -1));

        clearBtn.setBackground(new java.awt.Color(34, 162, 216));
        clearBtn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        clearBtn.setForeground(new java.awt.Color(255, 255, 255));
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        getContentPane().add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 457, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_backgrounds_images/Delete Q (1).png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Method ini menangani aksi tombol closeBtn untuk menutup frame DeleteQuestion.
     * @param evt Aksi event dari tombol closeBtn
     */
    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        AdminHome.open = 0;
        setVisible(false);
    }//GEN-LAST:event_closeBtnActionPerformed
    
    /**
     * Method ini menangani aksi tombol searchBtn untuk mencari pertanyaan berdasarkan ID.
     * @param evt Aksi event dari tombol searchBtn
     */
    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        String id = txtID.getText();
        
        if(id.isEmpty()){
            JOptionPane.showMessageDialog(this, "Isi ID pertanyaan/soal terlebih dahulu", "WARNING", JOptionPane.WARNING_MESSAGE);
        }else{
            try{
                Connection conn = ConnectionProvider.getConnected();
                Statement st = conn.createStatement();
                ResultSet rs = st.executeQuery("SELECT * FROM question WHERE id = '"+id+"'");

                if(rs.next()){
                    txtQuestion.setText(rs.getString(2));
                    txtOpt1.setText(rs.getString(3));
                    txtOpt2.setText(rs.getString(4));
                    txtOpt3.setText(rs.getString(5));
                    txtOpt4.setText(rs.getString(6));
                    txtAnswer.setText(rs.getString(7));
                    txtID.setEditable(false);
                    txtID.setFocusable(false);
                }else{
                    JFrame jf = new JFrame();
                    jf.setAlwaysOnTop(true);
                    JOptionPane.showMessageDialog(jf, "Question ID tidak ditemukan!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                }
            }catch(Exception e){
                JFrame jf = new JFrame();
                jf.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(jf, e);
            }
        }
    }//GEN-LAST:event_searchBtnActionPerformed
    
    /**
     * Method ini menangani aksi tombol deleteBtn untuk menghapus pertanyaan dari database.
     * @param evt Aksi event dari tombol deleteBtn
     */
    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        String id = txtID.getText();
        String name = txtQuestion.getText();
        String opt1 = txtOpt1.getText();
        String opt2 = txtOpt2.getText();
        String opt3 = txtOpt3.getText();
        String opt4 = txtOpt4.getText();
        String answer = txtAnswer.getText();
        
        if(id.isEmpty() && name.isEmpty() && opt1.isEmpty() && opt2.isEmpty() && opt3.isEmpty() && opt4.isEmpty() && answer.isEmpty()){
            JOptionPane.showMessageDialog(this, "Pertanyaan belum ditampilkan", "WARNING", JOptionPane.WARNING_MESSAGE);
        }else{
            try{
                Connection con = ConnectionProvider.getConnected();
                PreparedStatement ps = con.prepareStatement("DELETE FROM question WHERE id = ?");
                ps.setString(1, id);
                ps.executeUpdate();

                JFrame jf = new JFrame();
                jf.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(jf, "Pertanyaan berhasil dihapus", "Informasi", JOptionPane.INFORMATION_MESSAGE);

                setVisible(false);
                new DeleteQuestion().setVisible(true);
            }catch(Exception e){
                JFrame jf = new JFrame();
                jf.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(jf, e);
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed
    
    /**
     * Method ini menangani aksi tombol clearBtn untuk mengosongkan semua TextField.
     * @param evt Aksi event dari tombol clearBtn
     */
    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        txtID.setText("");
        txtQuestion.setText("");
        txtOpt1.setText("");
        txtOpt2.setText("");
        txtOpt3.setText("");
        txtOpt4.setText("");
        txtAnswer.setText("");
        txtID.setEditable(true);
        txtID.setFocusable(true);
    }//GEN-LAST:event_clearBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteQuestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton closeBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField txtAnswer;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtOpt1;
    private javax.swing.JTextField txtOpt2;
    private javax.swing.JTextField txtOpt3;
    private javax.swing.JTextField txtOpt4;
    private javax.swing.JTextField txtQuestion;
    // End of variables declaration//GEN-END:variables
}
