package DND_QUIZ;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.JOptionPane;

/**
 * Kelas untuk menampilkan instruksi sebelum memulai ujian kepada siswa.
 * Instruksi ini berisi tentang ketentuan-ketentuan yang harus diikuti
 * selama ujian berlangsung.
 * 
 * Instruksi ini juga menampilkan nomor pendaftaran siswa yang telah terdaftar.
 * 
 * @author DINA
 */
public class InstructionStudent extends javax.swing.JFrame {

    public String noDaftar;
    
    /**
     * Konstruktor default untuk menginisialisasi frame InstructionStudent.
     * Memanggil initComponents untuk inisialisasi komponen GUI.
     */
    public InstructionStudent() {
        initComponents();
    }
    
    /**
     * Konstruktor untuk menerima nomor pendaftaran dan menampilkannya pada frame.
     * @param noDaftar1 Nomor pendaftaran siswa yang terdaftar.
     */
    public InstructionStudent(String noDaftar1) {
        initComponents();
        JOptionPane.showMessageDialog(null, "Nomor Pendaftaran " + noDaftar1 + " terdaftar", "DATA TERDAFTAR", JOptionPane.INFORMATION_MESSAGE);
        jTextArea1.setEditable(false);
        noDaftar = noDaftar1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        startBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 84, 4, 15));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 22)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Selama ujian berlangsung:\n\n1. Siswa tidak boleh menggunakan buku teks, catatan kuliah, atau menerima bantuan dari \n   pengawas atau sumber lain dari luar.\n\n2. Siswa harus menyelesaikan ujian pilihan ganda sebanyak 10 pertanyaan yang dimana bersifat SEQUENTIAL.\n\n3. Siswa tidak boleh menghentikan sesi dan kemudian kembali lagi. Hal ini sangat penting dalam\n   lingkungan online di mana sistem akan “waktu habis” dan tidak mengizinkan siswa atau Anda untuk \n   masuk kembali ke ujian.\n\nJumlah Pertanyaan: 10\nSemoga berhasil!");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 1264, 467));

        startBtn.setBackground(new java.awt.Color(85, 161, 229));
        startBtn.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        startBtn.setForeground(new java.awt.Color(255, 255, 255));
        startBtn.setText("MULAI QUIZ");
        startBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnActionPerformed(evt);
            }
        });
        getContentPane().add(startBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 587, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_backgrounds_images/index student.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, -1, -1));

        jLabel3.setFont(new java.awt.Font("Algerian", 1, 50)); // NOI18N
        jLabel3.setText("instruction");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 22, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 82, 1370, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_backgrounds_images/pages background student.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Method yang dipanggil ketika tombol "MULAI QUIZ" ditekan.
     * Menyembunyikan frame ini dan menampilkan frame QuizExamStudent untuk memulai ujian.
     * @param evt Event dari tombol "MULAI QUIZ"
     */
    private void startBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtnActionPerformed
        setVisible(false);
        new QuizExamStudent(noDaftar).setVisible(true);
    }//GEN-LAST:event_startBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstructionStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstructionStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstructionStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstructionStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstructionStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton startBtn;
    // End of variables declaration//GEN-END:variables
}
