package DND_QUIZ;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * Kelas ini merupakan GUI untuk halaman login admin.
 * User dapat memasukkan username dan password untuk mengakses halaman admin.
 * Jika login berhasil, akan dialihkan ke halaman AdminHome.
 * Jika tidak, akan muncul pesan peringatan sesuai kondisi.
 * 
 * @author DAFFA
 */
public class LoginAdmin extends javax.swing.JFrame {

    /**
     * Konstruktor untuk membuat instance dari kelas LoginAdmin.
     * Inisialisasi komponen GUI.
     */
    public LoginAdmin() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsname = new javax.swing.JTextField();
        pwField = new javax.swing.JPasswordField();
        showPWBtn = new javax.swing.JRadioButton();
        lgnBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtUsname, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 270, 290, 60));

        pwField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(pwField, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 430, 290, 60));

        showPWBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        showPWBtn.setForeground(new java.awt.Color(33, 161, 218));
        showPWBtn.setText("Show Password");
        showPWBtn.setMaximumSize(new java.awt.Dimension(39, 40));
        showPWBtn.setPreferredSize(new java.awt.Dimension(35, 35));
        showPWBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPWBtnActionPerformed(evt);
            }
        });
        getContentPane().add(showPWBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 510, 160, 30));

        lgnBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lgnBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_backgrounds_images/tombol login (1).png"))); // NOI18N
        lgnBtn.setContentAreaFilled(false);
        lgnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgnBtnActionPerformed(evt);
            }
        });
        getContentPane().add(lgnBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 560, 120, -1));

        backBtn.setBackground(new java.awt.Color(48, 149, 220));
        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_backgrounds_images/tombol back (1).png"))); // NOI18N
        backBtn.setContentAreaFilled(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 560, 120, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_backgrounds_images/LOGIN STUDENT.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 1410, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Metode untuk menangani peristiwa saat tombol "Show Password" ditekan.
     * Jika checkbox dipilih, password field akan menampilkan karakter plaintext.
     * Jika tidak dipilih, password akan ditampilkan sebagai karakter bintang '*'.
     * 
     * @param evt Peristiwa yang dipicu oleh klik tombol "Show Password"
     */
    private void showPWBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPWBtnActionPerformed
        if(showPWBtn.isSelected()){
            pwField.setEchoChar((char)0);
        }else{
            pwField.setEchoChar('*');
        }
    }//GEN-LAST:event_showPWBtnActionPerformed
    
    /**
     * Metode untuk menangani peristiwa saat tombol "Login" ditekan.
     * Memeriksa username dan password yang dimasukkan.
     * Jika benar, mengalihkan ke halaman AdminHome.
     * Jika kosong, menampilkan pesan peringatan sesuai kondisi.
     * 
     * @param evt Peristiwa yang dipicu oleh klik tombol "Login"
     */
    private void lgnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgnBtnActionPerformed
        if(txtUsname.getText().equals("admin") && pwField.getText().equals("admin")){
            setVisible(false);
            new AdminHome().setVisible(true);
        }else if(txtUsname.getText().isEmpty() && pwField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Username dan Password harus diisi", "WARNING", JOptionPane.WARNING_MESSAGE);
        }else if(txtUsname.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Username harus diisi", "WARNING", JOptionPane.WARNING_MESSAGE);
        }else if(pwField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Password harus diisi", "WARNING", JOptionPane.WARNING_MESSAGE);
        }else{
            ImageIcon icon = new ImageIcon("Incorrect Password.PNG");
            JOptionPane.showMessageDialog(null, "<html><b style=\"color: red; font-size: 10px\">Username atau Password salah!</b></html>", "WARNING", JOptionPane.WARNING_MESSAGE, icon);
        }
    }//GEN-LAST:event_lgnBtnActionPerformed
    
    /**
     * Metode untuk menangani peristiwa saat tombol "Kembali" ditekan.
     * Mengalihkan kembali ke halaman utama (Index).
     * 
     * @param evt Peristiwa yang dipicu oleh klik tombol "Kembali"
     */
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        setVisible(false);
        new Index().setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton lgnBtn;
    private javax.swing.JPasswordField pwField;
    private javax.swing.JRadioButton showPWBtn;
    private javax.swing.JTextField txtUsname;
    // End of variables declaration//GEN-END:variables
}
