package DND_QUIZ;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import ConnectionProvider.ConnectionProvider;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 * Kelas Person merepresentasikan entitas pengguna dengan atribut username dan password.
 */
class Person {
    private String username;
    private String password;

    /**
     * Konstruktor untuk membuat objek Person baru dengan username dan password yang diberikan.
     * 
     * @param username nama pengguna
     * @param password kata sandi
     */
    public Person(String username, String password) {
        this.username = username;
        this.password = password;
    }

    /**
     * Mengembalikan username dari pengguna.
     * 
     * @return username
     */
    public String getUsername() {
        return username;
    }
    
    /**
     * Mengatur username pengguna.
     * 
     * @param username nama pengguna baru
     */
    public void setUsername(String username) {
        this.username = username;
    }
    
    /**
     * Mengembalikan password dari pengguna.
     * 
     * @return password
     */
    public String getPassword() {
        return password;
    }
    
    /**
     * Mengatur password pengguna.
     * 
     * @param password kata sandi baru
     */
    public void setPassword(String password) {
        this.password = password;
    }
}

/**
 * Kelas Student adalah subclass dari Person yang menambahkan atribut rePassword untuk konfirmasi kata sandi.
 */
class Student extends Person {
    private String rePassword;

    /**
     * Konstruktor untuk membuat objek Student baru dengan username, password, dan rePassword yang diberikan.
     * 
     * @param username nama pengguna
     * @param password kata sandi
     * @param rePassword konfirmasi kata sandi
     */
    public Student(String username, String password, String rePassword) {
        super(username, password);
        this.rePassword = rePassword;
    }

    /**
     * Mengembalikan rePassword dari pengguna.
     * 
     * @return rePassword
     */
    public String getRePassword() {
        return rePassword;
    }
    
    /**
     * Mengatur rePassword pengguna.
     * 
     * @param rePassword konfirmasi kata sandi baru
     */
    public void setRePassword(String rePassword) {
        this.rePassword = rePassword;
    }
}

/**
 * Kelas RegisterStudent adalah JFrame yang digunakan untuk melakukan registrasi pengguna baru.
 * Kelas ini menyediakan antarmuka pengguna untuk memasukkan username, password, dan konfirmasi password.
 * 
 * @author DAFFA
 */
public class RegisterStudent extends javax.swing.JFrame implements ExceptionError {

    /**
     * Membuat form baru dari RegisterStudent.
     * Konstruktor ini memanggil metode initComponents untuk menginisialisasi komponen form.
     */
    public RegisterStudent() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsname = new javax.swing.JTextField();
        pwField = new javax.swing.JPasswordField();
        repwField = new javax.swing.JPasswordField();
        showPWBtn = new javax.swing.JRadioButton();
        lgnBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lgnHereBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtUsname, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 220, 290, 40));

        pwField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(pwField, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 310, 290, 40));

        repwField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(repwField, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 410, 290, 40));

        showPWBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        showPWBtn.setForeground(new java.awt.Color(33, 161, 218));
        showPWBtn.setText("Show Password");
        showPWBtn.setMaximumSize(new java.awt.Dimension(39, 40));
        showPWBtn.setPreferredSize(new java.awt.Dimension(35, 35));
        showPWBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPWBtnActionPerformed(evt);
            }
        });
        getContentPane().add(showPWBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 470, 160, 30));

        lgnBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lgnBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_backgrounds_images/tombol login (1).png"))); // NOI18N
        lgnBtn.setContentAreaFilled(false);
        lgnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgnBtnActionPerformed(evt);
            }
        });
        getContentPane().add(lgnBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 530, 120, -1));

        backBtn.setBackground(new java.awt.Color(48, 149, 220));
        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_backgrounds_images/tombol back (1).png"))); // NOI18N
        backBtn.setContentAreaFilled(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 530, 120, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(34, 162, 216));
        jLabel1.setText("Already have an account?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 620, -1, 30));

        lgnHereBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lgnHereBtn.setForeground(new java.awt.Color(34, 162, 216));
        lgnHereBtn.setText("Login here");
        lgnHereBtn.setContentAreaFilled(false);
        lgnHereBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgnHereBtnActionPerformed(evt);
            }
        });
        getContentPane().add(lgnHereBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 620, -1, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_backgrounds_images/REGIS STUDENT.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 1410, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Metode ini dipanggil ketika tombol 'Show Password' ditekan.
     * Menampilkan atau menyembunyikan karakter kata sandi berdasarkan pilihan pengguna.
     * 
     * @param evt peristiwa yang dipicu oleh klik tombol Tampilkan Kata Sandi
     */
    private void showPWBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPWBtnActionPerformed
        if(showPWBtn.isSelected()){
            pwField.setEchoChar((char)0);
            repwField.setEchoChar((char)0);
        }else{
            pwField.setEchoChar('*');
            repwField.setEchoChar('*');
        }
    }//GEN-LAST:event_showPWBtnActionPerformed
    
    /**
     * Metode ini dipanggil ketika tombol 'Login' ditekan.
     * Memproses data input dari pengguna dan melakukan validasi serta registrasi pengguna baru.
     * 
     * @param evt peristiwa yang dipicu oleh klik tombol Login
     */
    private void lgnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgnBtnActionPerformed
        String usname = txtUsname.getText();
        String pw = new String(pwField.getPassword());
        String repw = new String(repwField.getPassword());
        
        Person person = new Student(usname, pw, repw); // Upcasting
        
        if(person instanceof Student){ //Cek InstanceOf
            Student student = (Student) person; //Downcasting
            
            if(student.getUsername().isEmpty() && student.getPassword().isEmpty() && student.getRePassword().isEmpty()){
                JOptionPane.showMessageDialog(this, "Username dan Password belum diisi", "WARNING", JOptionPane.WARNING_MESSAGE);
            }else{
                if(student.getUsername().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Username belum diisi", "WARNING", JOptionPane.WARNING_MESSAGE);
                }else{
                    if(student.getPassword().isEmpty()){
                        JOptionPane.showMessageDialog(this, "Password belum diisi", "WARNING", JOptionPane.WARNING_MESSAGE);
                    }else{
                        if(student.getRePassword().isEmpty()){
                            JOptionPane.showMessageDialog(this, "Tuliskan kembali password pada kolom re-password", "WARNING", JOptionPane.WARNING_MESSAGE);
                        }else{
                            if(student.getPassword().length() < 8){
                                JOptionPane.showMessageDialog(this, "Panjang password harus minimal 8 karakter", "WARNING", JOptionPane.WARNING_MESSAGE);
                            }else{
                                if(student.getPassword().equals(student.getRePassword())){
                                    try{
                                        Statement state = ConnectionProvider.getConnected().createStatement();

                                        if(isUsnameTaken(usname)){
                                            JOptionPane.showMessageDialog(this, "Username ini sudah digunakan", "WARNING", JOptionPane.WARNING_MESSAGE);
                                        }else{
                                            state.executeUpdate("INSERT INTO data_username_password (username, password) values ('"+usname+"','"+pw+"')");
                                            JOptionPane.showMessageDialog(this, "Registrasi Berhasil", "INFORMASI", JOptionPane.INFORMATION_MESSAGE);

                                            this.setVisible(false);
                                            new LoginStudent().setVisible(true);

                                            reset();
                                        }
                                    }catch(Exception e){
                                        ExceptionError.errorMessage(e);
                                    }
                                }else{
                                    JOptionPane.showMessageDialog(this, "Password tidak sesuai", "WARNING", JOptionPane.WARNING_MESSAGE);
                                }
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_lgnBtnActionPerformed
    
    /**
     * Metode ini dipanggil ketika tombol 'Back' ditekan.
     * Menyembunyikan jendela saat ini dan menampilkan jendela indeks.
     * 
     * @param evt peristiwa yang dipicu oleh klik tombol Kembali
     */
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        setVisible(false);
        new Index().setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed
    
    /**
     * Metode ini dipanggil ketika tombol 'Login here' ditekan.
     * Menyembunyikan jendela saat ini dan menampilkan jendela login siswa.
     * 
     * @param evt peristiwa yang dipicu oleh klik tombol Login di sini
     */
    private void lgnHereBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgnHereBtnActionPerformed
        setVisible(false);
        new LoginStudent().setVisible(true);
    }//GEN-LAST:event_lgnHereBtnActionPerformed
    
    /**
     * Memeriksa apakah username sudah digunakan oleh pengguna lain.
     * 
     * @param usname nama pengguna yang akan diperiksa
     * @return true jika username sudah digunakan, false jika belum
     * @throws SQLException jika terjadi kesalahan SQL
     */
    private boolean isUsnameTaken(String usname) throws SQLException {
        Statement state = ConnectionProvider.getConnected().createStatement();
        ResultSet resSet = state.executeQuery("SELECT * FROM data_username_password WHERE username = '" + usname + "'");
        return resSet.next();
    }
    
    /**
     * Mengatur ulang input form menjadi kosong.
     */
    private void reset(){
        txtUsname.setText("");
        pwField.setText("");
        repwField.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton lgnBtn;
    private javax.swing.JButton lgnHereBtn;
    private javax.swing.JPasswordField pwField;
    private javax.swing.JPasswordField repwField;
    private javax.swing.JRadioButton showPWBtn;
    private javax.swing.JTextField txtUsname;
    // End of variables declaration//GEN-END:variables
}
