package DND_QUIZ;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import ConnectionProvider.ConnectionProvider;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;

/**
 * Kelas StudentDetails mengatur detail dari pendaftaran siswa.
 * Kelas ini menampilkan form untuk diisi oleh siswa dan menyimpan data ke database.
 * 
 * @author DAFFA
 */
public class StudentDetails extends javax.swing.JFrame implements ExceptionError {

    /**
     * Konstruktor untuk inisialisasi frame, komponen GUI, dan pengaturan awal.
     * Mengambil tanggal saat ini dan menampilkan nomor pendaftaran otomatis.
     * Juga menginisialisasi combo box fakultas dengan pilihan dan mengaitkan listener.
     */
    public StudentDetails() {
        initComponents();
        
        jTextArea1.setEditable(false);
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date date = new Date();
        lblDateDisplay.setText(dateFormat.format(date));
        
        try{
            Connection conn = ConnectionProvider.getConnected();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT COUNT(no_pendaftaran) FROM studentdata");
            
            if(rs.next()){
                int id = rs.getInt(1);
                id = id + 1;
                
                String str = String.valueOf(id);
                txtNoPendaftaran.setText(str);
                txtNoPendaftaran.setFocusable(false);
            }else{
                txtNoPendaftaran.setText("1");
            }
        }catch(Exception e){
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf, e);
        }
        
        //Kelas Anonim untuk menangani event dari combobox fakultas
        cmbFakultas.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                String fakultas = cmbFakultas.getSelectedItem().toString();
                updateProdiCombo(fakultas);
            }
        });
    }
    
    /**
     * Method untuk meng-update combo box program studi (prodi) berdasarkan fakultas yang dipilih.
     * @param fakultas String yang mewakili fakultas yang dipilih oleh pengguna.
     */
    private void updateProdiCombo(String fakultas) {
        cmbProdi.removeAllItems();
        cmbProdi.addItem("Pilih Prodi");
        
        if(fakultas.equals("Kedokteran")) {
            cmbProdi.addItem("Kedokteran");
            cmbProdi.addItem("Profesi Dokter");
        } else if(fakultas.equals("Kedokteran Gigi")) {
            cmbProdi.addItem("Pendidikan Dokter Gigi");
            cmbProdi.addItem("Profesi Dokter Gigi");
        } else if(fakultas.equals("Teknologi Informasi")) {
            cmbProdi.addItem("Teknik Informatika");
            cmbProdi.addItem("PDSI");
        } else if(fakultas.equals("Hukum")) {
            cmbProdi.addItem("Ilmu Hukum");
        } else if(fakultas.equals("Ekonomi dan Bisnis")) {
            cmbProdi.addItem("Manajemen");
            cmbProdi.addItem("Akuntansi");
        } else if(fakultas.equals("Psikologi")) {
            cmbProdi.addItem("Psikologi");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblDateDisplay = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNoPendaftaran = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtNPM = new javax.swing.JTextField();
        txtNomorTelepon = new javax.swing.JTextField();
        cmbKelamin = new javax.swing.JComboBox<>();
        txtEmail = new javax.swing.JTextField();
        txtUnivName = new javax.swing.JTextField();
        cmbFakultas = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        saveAndNextBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        cmbProdi = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_backgrounds_images/index student.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, -1, -1));

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 40)); // NOI18N
        jLabel2.setText("fill up the form");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 22, -1, -1));

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblDate.setText("Date:");
        getContentPane().add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, -1, -1));

        lblDateDisplay.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblDateDisplay.setText(".");
        getContentPane().add(lblDateDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, -1, -1));

        backBtn.setBackground(new java.awt.Color(85, 161, 229));
        backBtn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 10, 120, 70));

        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_backgrounds_images/logo exit (1).png"))); // NOI18N
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 10, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 82, 1370, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setText("Nomor Pendaftaran");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setText("Nama");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setText("Nomor Pokok Mahasiswa");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setText("Jenis Kelamin");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setText("Nomor Telepon");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel8.setText("Email");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel9.setText("Universitas");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel11.setText("Fakultas");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel12.setText("Prodi");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));

        txtNoPendaftaran.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtNoPendaftaran.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(txtNoPendaftaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 120, -1));

        txtNama.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtNama.setForeground(new java.awt.Color(204, 204, 204));
        txtNama.setText("Masukkan Nama");
        txtNama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNamaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNamaFocusLost(evt);
            }
        });
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 320, -1));

        txtNPM.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtNPM.setForeground(new java.awt.Color(204, 204, 204));
        txtNPM.setText("Masukkan NPM");
        txtNPM.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNPMFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNPMFocusLost(evt);
            }
        });
        getContentPane().add(txtNPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 320, -1));

        txtNomorTelepon.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtNomorTelepon.setForeground(new java.awt.Color(204, 204, 204));
        txtNomorTelepon.setText("Masukkan Nomor Telepon");
        txtNomorTelepon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomorTeleponFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomorTeleponFocusLost(evt);
            }
        });
        getContentPane().add(txtNomorTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 320, -1));

        cmbKelamin.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        cmbKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jenis Kelamin", "Pria", "Wanita" }));
        getContentPane().add(cmbKelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 320, -1));

        txtEmail.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(204, 204, 204));
        txtEmail.setText("Masukkan Email");
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 320, -1));

        txtUnivName.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtUnivName.setForeground(new java.awt.Color(204, 204, 204));
        txtUnivName.setText("Masukkan Nama Universitas");
        txtUnivName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUnivNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUnivNameFocusLost(evt);
            }
        });
        getContentPane().add(txtUnivName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 530, 320, -1));

        cmbFakultas.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        cmbFakultas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Fakultas", "Kedokteran", "Kedokteran Gigi", "Teknologi Informasi", "Hukum", "Ekonomi dan Bisnis", "Psikologi" }));
        getContentPane().add(cmbFakultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 320, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel13.setText("Alamat");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, -1, -1));

        txtAlamat.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtAlamat.setForeground(new java.awt.Color(204, 204, 204));
        txtAlamat.setText("Masukkan Alamat");
        txtAlamat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAlamatFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAlamatFocusLost(evt);
            }
        });
        getContentPane().add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 580, 580, -1));

        saveAndNextBtn.setBackground(new java.awt.Color(85, 161, 229));
        saveAndNextBtn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        saveAndNextBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveAndNextBtn.setText("Save & Next");
        saveAndNextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAndNextBtnActionPerformed(evt);
            }
        });
        getContentPane().add(saveAndNextBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 640, 320, 50));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("SEMANGAT UJIANNYA!");
        jTextArea1.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 580, 230));

        cmbProdi.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        cmbProdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Prodi" }));
        getContentPane().add(cmbProdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 320, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_backgrounds_images/pages background student.jpg"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Method ini menangani aksi tombol keluar, menampilkan dialog konfirmasi sebelum keluar.
     * @param evt Objek ActionEvent yang merepresentasikan event saat tombol diklik.
     */
    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Apakah kamu benar ingin keluar aplikasi?", "SELECT OPTION", JOptionPane.YES_NO_OPTION);

        if(a == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_closeBtnActionPerformed
    
    private void txtUnivNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUnivNameFocusGained
        if(txtUnivName.getText().equals("Masukkan Nama Universitas")){
            txtUnivName.setText("");
            txtUnivName.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtUnivNameFocusGained
    
    private void txtUnivNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUnivNameFocusLost
        if(txtUnivName.getText().equals("")){
            txtUnivName.setText("Masukkan Nama Universitas");
            txtUnivName.setForeground(new Color(255, 255, 255));
        }
    }//GEN-LAST:event_txtUnivNameFocusLost
    
    /**
     * Method ini menangani aksi tombol "Simpan & Lanjutkan".
     * Memvalidasi isian form sebelum menyimpan data ke database.
     * Jika ada field yang belum terisi atau tidak valid, akan menampilkan pesan kesalahan.
     * @param evt Objek ActionEvent yang merepresentasikan event saat tombol diklik.
     */
    private void saveAndNextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAndNextBtnActionPerformed
        String noDaftar = txtNoPendaftaran.getText();
        String namaMahasiswa = txtNama.getText();
        String npm = txtNPM.getText();
        String kelamin = cmbKelamin.getSelectedItem().toString();
        String email = txtEmail.getText();
        String noTelp = txtNomorTelepon.getText();
        String fakultas = cmbFakultas.getSelectedItem().toString();
        String prodi = cmbProdi.getSelectedItem().toString();
        String namaUniv = txtUnivName.getText();
        String alamat = txtAlamat.getText();
        String nilai = "0";
        
        if(namaMahasiswa.equals("Masukkan Nama") && npm.equals("Masukkan NPM") && kelamin.equals("Pilih Jenis Kelamin") && email.equals("Masukkan Email") && noTelp.equals("Masukkan Nomor Telepon") && fakultas.equals("Pilih Fakultas") && prodi.equals("Pilih Prodi") && namaUniv.equals("Masukkan Nama Universitas") && alamat.equals("Masukkan Alamat")){
            JOptionPane.showMessageDialog(this, "Form harus terisi!", "WARNING", JOptionPane.WARNING_MESSAGE);
        }else{
            if(namaMahasiswa.equals("Masukkan Nama")){
                JOptionPane.showMessageDialog(this, "Nama harus terisi!", "WARNING", JOptionPane.WARNING_MESSAGE);
            }else{
                if(npm.equals("Masukkan NPM")){
                    JOptionPane.showMessageDialog(this, "NPM harus terisi!", "WARNING", JOptionPane.WARNING_MESSAGE);
                }else{
                    if(!npm.matches("\\d+")){
                        JOptionPane.showMessageDialog(this, "NPM harus mengandung angka!", "WARNING", JOptionPane.WARNING_MESSAGE);
                    }else{
                        if(npm.length() != 10){
                            JOptionPane.showMessageDialog(this, "NPM harus berjumlah 10 digit!", "WARNING", JOptionPane.WARNING_MESSAGE);
                        }else{
                            if(kelamin.equals("Pilih Jenis Kelamin")){
                                JOptionPane.showMessageDialog(this, "Pilih jenis kelamin anda!", "WARNING", JOptionPane.WARNING_MESSAGE);
                            }else{
                                if(email.equals("Masukkan Email")){
                                    JOptionPane.showMessageDialog(this, "Email harus terisi!", "WARNING", JOptionPane.WARNING_MESSAGE);
                                }else{
                                    if(!email.contains("@")){
                                        JOptionPane.showMessageDialog(this, "Email tidak valid!", "WARNING", JOptionPane.WARNING_MESSAGE);
                                    }else{
                                        if(noTelp.equals("Masukkan Nomor Telepon")){
                                            JOptionPane.showMessageDialog(this, "Nomor Telepon harus terisi!", "WARNING", JOptionPane.WARNING_MESSAGE);
                                        }else{
                                            if(!noTelp.matches("\\d+")){
                                                JOptionPane.showMessageDialog(this, "Nomor Telepon harus mengandung angka!", "WARNING", JOptionPane.WARNING_MESSAGE);
                                            }else{
                                                if(noTelp.length() < 10){
                                                    JOptionPane.showMessageDialog(this, "Nomor Telepon minimal berjumlah 10 digit!", "WARNING", JOptionPane.WARNING_MESSAGE);
                                                }else{
                                                    if(fakultas.equals("Pilih Fakultas")){
                                                        JOptionPane.showMessageDialog(this, "Pilih sesuai dengan Fakultas anda!", "WARNING", JOptionPane.WARNING_MESSAGE);
                                                    }else{
                                                        if(prodi.equals("Pilih Prodi")){
                                                            JOptionPane.showMessageDialog(this, "Pilih sesuai dengan Prodi anda!", "WARNING", JOptionPane.WARNING_MESSAGE);
                                                        }else{
                                                            if(namaUniv.equals("Masukkan Nama Universitas")){
                                                                JOptionPane.showMessageDialog(this, "Asal Universitas harus terisi!", "WARNING", JOptionPane.WARNING_MESSAGE);
                                                            }else{
                                                                if(alamat.equals("Masukkan Alamat")){
                                                                    JOptionPane.showMessageDialog(this, "Alamat harus terisi!", "WARNING", JOptionPane.WARNING_MESSAGE);
                                                                }else{
                                                                    try{
                                                                        Connection cont = ConnectionProvider.getConnected();
                                                                        PreparedStatement ps = cont.prepareStatement("INSERT INTO studentdata VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
                                                                        ps.setString(1, noDaftar);
                                                                        ps.setString(2, namaMahasiswa);
                                                                        ps.setString(3, npm);
                                                                        ps.setString(4, kelamin);
                                                                        ps.setString(5, email);
                                                                        ps.setString(6, noTelp);
                                                                        ps.setString(7, fakultas);
                                                                        ps.setString(8, prodi);
                                                                        ps.setString(9, namaUniv);
                                                                        ps.setString(10, alamat);
                                                                        ps.setString(11, nilai);
                                                                        ps.executeUpdate();

                                                                        JOptionPane.showMessageDialog(this, "Datamu berhasil tersimpan", "INFORMASI", JOptionPane.INFORMATION_MESSAGE);

                                                                        setVisible(false);
                                                                        new InstructionStudent(noDaftar).setVisible(true);
                                                                    }catch(Exception e){
                                                                         ExceptionError.errorMessage(e);
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_saveAndNextBtnActionPerformed
    
    /**
     * Method ini menangani aksi tombol "Kembali" untuk kembali ke halaman sebelumnya.
     * @param evt Objek ActionEvent yang merepresentasikan event saat tombol diklik.
     */
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        setVisible(false);
        new Index().setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void txtNamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNamaFocusGained
        if(txtNama.getText().equals("Masukkan Nama")){
            txtNama.setText("");
            txtNama.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtNamaFocusGained

    private void txtNamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNamaFocusLost
        if(txtNama.getText().equals("")){
            txtNama.setText("Masukkan Nama");
            txtNama.setForeground(new Color(255, 255, 255));
        }
    }//GEN-LAST:event_txtNamaFocusLost

    private void txtNPMFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNPMFocusGained
        if(txtNPM.getText().equals("Masukkan NPM")){
            txtNPM.setText("");
            txtNPM.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtNPMFocusGained

    private void txtNPMFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNPMFocusLost
        if(txtNPM.getText().equals("")){
            txtNPM.setText("Masukkan NPM");
            txtNPM.setForeground(new Color(255, 255, 255));
        }
    }//GEN-LAST:event_txtNPMFocusLost

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        if(txtEmail.getText().equals("Masukkan Email")){
            txtEmail.setText("");
            txtEmail.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        if(txtEmail.getText().equals("")){
            txtEmail.setText("Masukkan Email");
            txtEmail.setForeground(new Color(255, 255, 255));
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtNomorTeleponFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomorTeleponFocusGained
        if(txtNomorTelepon.getText().equals("Masukkan Nomor Telepon")){
            txtNomorTelepon.setText("");
            txtNomorTelepon.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtNomorTeleponFocusGained

    private void txtNomorTeleponFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomorTeleponFocusLost
        if(txtNomorTelepon.getText().equals("")){
            txtNomorTelepon.setText("Masukkan Nomor Telepon");
            txtNomorTelepon.setForeground(new Color(255, 255, 255));
        }
    }//GEN-LAST:event_txtNomorTeleponFocusLost

    private void txtAlamatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAlamatFocusGained
        if(txtAlamat.getText().equals("Masukkan Alamat")){
            txtAlamat.setText("");
            txtAlamat.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtAlamatFocusGained

    private void txtAlamatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAlamatFocusLost
        if(txtAlamat.getText().equals("")){
            txtAlamat.setText("Masukkan Alamat");
            txtAlamat.setForeground(new Color(255, 255, 255));
        }
    }//GEN-LAST:event_txtAlamatFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton closeBtn;
    private javax.swing.JComboBox<String> cmbFakultas;
    private javax.swing.JComboBox<String> cmbKelamin;
    private javax.swing.JComboBox<String> cmbProdi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDateDisplay;
    private javax.swing.JButton saveAndNextBtn;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNPM;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoPendaftaran;
    private javax.swing.JTextField txtNomorTelepon;
    private javax.swing.JTextField txtUnivName;
    // End of variables declaration//GEN-END:variables
}
