/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import Project.ConnectionProvider;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;

/**
 *
 * @author DAFFA
 */
public class studentDetails extends javax.swing.JFrame {

    /**
     * Creates new form studentDetails
     */
    public studentDetails() {
        initComponents();
        
        jTextArea1.setEditable(false);
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date date = new Date();
        lblDateDisplay.setText(dateFormat.format(date));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblDateDisplay = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNoPendaftaran = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtNPM = new javax.swing.JTextField();
        txtNomorTelepon = new javax.swing.JTextField();
        cmbKelamin = new javax.swing.JComboBox<>();
        txtEmail = new javax.swing.JTextField();
        txtUnivName = new javax.swing.JTextField();
        cmbFakultas = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        saveAndNextBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        cmbProdi = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/index student.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, -1, -1));

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 40)); // NOI18N
        jLabel2.setText("fill up the form");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 22, -1, -1));

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblDate.setText("Date:");
        getContentPane().add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, -1, -1));

        lblDateDisplay.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblDateDisplay.setText(".");
        getContentPane().add(lblDateDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, -1, -1));

        backBtn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back student.png"))); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, -1, -1));

        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo exit (1).png"))); // NOI18N
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 10, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 82, 1370, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setText("Nomor Pendaftaran");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setText("Nama");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setText("Nomor Pokok Mahasiswa");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setText("Jenis Kelamin");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setText("Nomor Telepon");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel8.setText("Email");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel9.setText("Universitas");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel11.setText("Fakultas");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel12.setText("Prodi");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));

        txtNoPendaftaran.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        getContentPane().add(txtNoPendaftaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 320, -1));

        txtNama.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 320, -1));

        txtNPM.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        getContentPane().add(txtNPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 320, -1));

        txtNomorTelepon.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        getContentPane().add(txtNomorTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 320, -1));

        cmbKelamin.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        cmbKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jenis Kelamin", "Pria", "Wanita" }));
        getContentPane().add(cmbKelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 320, -1));

        txtEmail.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 320, -1));

        txtUnivName.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtUnivName.setForeground(new java.awt.Color(204, 204, 204));
        txtUnivName.setText("Masukkan Nama Universitas");
        txtUnivName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUnivNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUnivNameFocusLost(evt);
            }
        });
        getContentPane().add(txtUnivName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 530, 320, -1));

        cmbFakultas.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        cmbFakultas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Fakultas", "Kedokteran", "Kedokteran Gigi", "Teknologi Informasi", "Hukum", "Ekonomi dan Bisnis", "Psikologi" }));
        getContentPane().add(cmbFakultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 320, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel13.setText("Alamat");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, -1, -1));

        txtAlamat.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        getContentPane().add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 580, 580, -1));

        saveAndNextBtn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        saveAndNextBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        saveAndNextBtn.setText("Save & Next");
        saveAndNextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAndNextBtnActionPerformed(evt);
            }
        });
        getContentPane().add(saveAndNextBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 640, 320, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Himbauan kepada semua peserta ujian untuk membawa kartu identitas dan alat tulis dengan lengkap serta tidak mencontek selama ujian berlangsung.\nSemoga berhasil untuk ujiannya! \nTetaplah percaya kepada diri sendiri dan kamu pasti akan mencapai setiap tujuanmu!\n");
        jTextArea1.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 580, 230));

        cmbProdi.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        cmbProdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Prodi", "Kedokteran", "Profesi Dokter", "Pendidikan Dokter Gigi", "Profesi Dokter Gigi", "Psikologi", "Manajemen", "Akuntansi", "Ilmu Hukum", "Teknik Informatika", "Perpustakaan dan Sains Informasi" }));
        getContentPane().add(cmbProdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 320, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pages background student.jpg"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        setVisible(false);
        new index().setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to Exit Application?", "Select", JOptionPane.YES_NO_OPTION);

        if(a == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_closeBtnActionPerformed

    private void txtUnivNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUnivNameFocusGained
        if(txtUnivName.getText().equals("Masukkan Nama Universitas")){
            txtUnivName.setText("");
            txtUnivName.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtUnivNameFocusGained

    private void txtUnivNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUnivNameFocusLost
        if(txtUnivName.getText().equals("")){
            txtUnivName.setText("Masukkan Nama Universitas");
            txtUnivName.setForeground(new Color(255, 255, 255));
        }
    }//GEN-LAST:event_txtUnivNameFocusLost

    private void saveAndNextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAndNextBtnActionPerformed
        String noDaftar = txtNoPendaftaran.getText();
        String namaMahasiswa = txtNama.getText();
        String npm = txtNPM.getText();
        String kelamin = cmbKelamin.getSelectedItem().toString();
        String email = txtEmail.getText();
        String noTelp = txtNomorTelepon.getText();
        String fakultas = cmbFakultas.getSelectedItem().toString();
        String prodi = cmbProdi.getSelectedItem().toString();
        String namaUniv = txtUnivName.getText();
        String alamat = txtAlamat.getText();
        String nilai = "0";
        
        try{
            Connection cont = ConnectionProvider.getConnected();
            PreparedStatement ps = cont.prepareStatement("INSERT INTO studentdata VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
            ps.setString(1, noDaftar);
            ps.setString(2, namaMahasiswa);
            ps.setString(3, npm);
            ps.setString(4, kelamin);
            ps.setString(5, email);
            ps.setString(6, noTelp);
            ps.setString(7, fakultas);
            ps.setString(8, prodi);
            ps.setString(9, namaUniv);
            ps.setString(10, alamat);
            ps.setString(11, nilai);
            ps.executeUpdate();
            
            setVisible(false);
            new InstructionStudent(noDaftar).setVisible(true);
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_saveAndNextBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton closeBtn;
    private javax.swing.JComboBox<String> cmbFakultas;
    private javax.swing.JComboBox<String> cmbKelamin;
    private javax.swing.JComboBox<String> cmbProdi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDateDisplay;
    private javax.swing.JButton saveAndNextBtn;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNPM;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoPendaftaran;
    private javax.swing.JTextField txtNomorTelepon;
    private javax.swing.JTextField txtUnivName;
    // End of variables declaration//GEN-END:variables
}
